services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:42001:8000"
    environment:
      - LMS_API_KEY=my-secret-api-key
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lms-network

  postgres:
    image: harbor.pg.innopolis.university/docker-hub-cache/postgres:18.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db-lab-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:42004:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lms-network

  caddy:
    build: frontend/
    restart: unless-stopped
    ports:
      - "0.0.0.0:42002:80"
    depends_on:
      - backend
    environment:
      - BACKEND_CONTAINER_PORT=8000
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - lms-network
  nanobot:
    image: alpine
    command: sh -c "echo 'nanobot ready' && tail -f /dev/null"
    restart: unless-stopped
    networks:
      - lms-network
    environment:
      - NANOBOT_ACCESS_KEY=my-access-key

volumes:
  postgres_data:

networks:
  lms-network:
    name: lms-network
    attachable: true
